name: Repository Checks

on: [ pull_request ]

jobs:
  semi_linear_history_check:
    uses: ./system/.github/actions/repo_checks.yml@master

  submodule_master_check:

    name: System Submodule is on master

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Check if submodule is on master
        uses: jtmullen/submodule-branch-check-action@v1
        with:
          path: "system"
          branch: "master"
          pass_if_unchanged: true

  submodule_most_recent_master_check:

    name: System Submodule is on most recent master

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Check if submodule is on most recent master commit
        uses: jtmullen/submodule-branch-check-action@v1
        with:
          path: "system"
          branch: "master"
          require_head: true
