name: PyTest

on: [push]

jobs:

  tests:
  
    name: Run Unit Tests

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Upgrade pip
      run: pip install --upgrade pip
      
#    - name: Cache pip
#      uses: actions/cache@v2
#      with:
#        path: ~/.cache/pip
#        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
#        restore-keys:
#          ${{ runner.os }}-pip-

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
#      run:
#        python -m pip install --upgrade pipenv wheel

#    - name: Cache Pipenv
#      id: cache-pipenv
#      uses: actions/cache@v1
#      with:
#        path: ~/.local/share/virtualenvs
#        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install dependencies
#      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run:
        pipenv install
#        pipenv install --deploy --dev

    - name: Run Pipenv Check
      run: pipenv check

    - name: Run Tests
      run: pipenv run python -m pytest -m "not network and not github_skip" --cov ./ --cov-branch
