name: PyTest

on: [push]

jobs:

  tests:
  
    name: Run Unit Tests

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Upgrade pip
      run: pip install --upgrade pip

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1

    - name: Install dependencies
      run:
        pipenv install
#        pipenv install --deploy --dev

    - name: Run Pipenv Check
      run: pipenv check

    - name: Run Tests
      run: pipenv run python -m pytest -m "not network and not github_skip and not runtime and not client" --cov ./ --cov-branch
